---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, cloud manager, NetApp Console
summary: Learn what's new in Amazon FSx for NetApp ONTAP.
---
= What's new with Amazon FSx for NetApp ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in FSx for ONTAP.

== 09 February 2026

include::_whatsnew/2026-02-09.adoc[]

== 17 November 2025

include::_whatsnew/2025-11-17.adoc[]

== 11 November 2025

include::_whatsnew/2025-11-11.adoc[]

== 06 October 2025

include::_whatsnew/2025-10-06.adoc[]

== 03 August 2025

include::_whatsnew/2025-08-03.adoc[]

== 14 July 2025

include::_whatsnew/2025-07-14.adoc[]

== 29 June 2025

include::_whatsnew/2025-06-29.adoc[]

== 04 May 2025

include::_whatsnew/2025-05-04.adoc[]

== 30 March 2025
include::_whatsnew/2025-03-30.adoc[]

== 02 March 2025
include::_whatsnew/2025-03-02.adoc[]

== 02 February 2025
include::_whatsnew/2025-02-02.adoc[]

== 06 January 2025
include::_whatsnew/2025-01-06.adoc[]

== 11 November 2024
include::_whatsnew/2024-11-11.adoc[]

== 30 July 2023
include::_whatsnew/2023-07-30.adoc[]

== 02 July 2023
include::_whatsnew/2023-07-02.adoc[]

== 04 June 2023
include::_whatsnew/2023-06-04.adoc[]

== 07 May 2023
=== Generate a security group
When creating a working environment, you can now have BlueXP link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-create-fsx-system.html[generate a security group] that allows traffic within the selected VPC only. This feature link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/requirements/task-setting-up-permissions-fsx.html[requires additional permissions]. 

=== Add or modify tags
You can optionally add and modify tags to categorize volumes. 

== 02 April 2023
=== Increase in IOPS limit
The IOPS limit is increased to allow manual or automatic provisioning up to 160,000. 

== 05 March 2023
=== User interface enhanced
User interface improvements have been made and screenshots have been updated in the documentation. 

== 01 January 2023
=== Automatic capacity management
You can now choose to enable link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html[automatic capacity management] to add incremental storage based on demand. Automatic capacity management polls the cluster at regular intervals to assess demand and automatically increases storage capacity in increments of 10% up to 80% of the cluster's maximum capacity.

== 18 September 2022
=== Change storage capacity and IOPS
You can now link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html[change the storage capacity and IOPS] at any time after you create the FSx for ONTAP working environment. 

== 31 July 2022
=== *My estate* feature
If you previously provided your AWS credentials to Cloud Manager, the new *My estate* feature can automatically discover and suggest FSx for ONTAP file systems to add and manage using Cloud Manager. You can also review available data services through the *My estate* tab. 

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-create-fsx-system.html#discover-an-existing-fsx-for-ontap-file-system[Discover FSx for ONTAP using My estate]

=== Change throughput capacity
You can now link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html[change throughput capacity] at any time after you create the FSx for ONTAP working environment.

=== Replicate and sync data
You can now replicate and sync data to on-premises and other FSx for ONTAP systems using FSx for ONTAP as the source. 

=== Create iSCSI volume
You can now create iSCSI volumes in FSx for ONTAP using Cloud Manager. 

== 3 July 2022
=== Support for single or multiple Availability Zon
You can now select a single or multiple Availability Zone HA deployment model.

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-create-fsx-system.html[Create an FSx for ONTAP working environment]

=== Support for GovCloud account authentication
AWS GovCloud account authentication is now supported in Cloud Manager. 

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/requirements/task-setting-up-permissions-fsx.html#set-up-the-iam-role[Set up the IAM role]

== 27 February 2022
=== Assume IAM role
When you create an FSx for ONTAP working environment, you now must provide the ARN of an IAM role that Cloud Manager can assume to create an FSx for ONTAP working environment. You previously needed to provide AWS access keys.

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/requirements/task-setting-up-permissions-fsx.html[Learn how to set up permissions for FSx for ONTAP].

== 31 October 2021
=== Create iSCSI volumes using Cloud Manager API
You can create iSCSI volumes for FSx for ONTAP using the Cloud Manager API and manage them in your working environment.

=== Select volume units when creating volumes
You can elect volume units (GiB or TiB) when creating volumes in FSx for ONTAP.

== 4 October 2021
=== Create CIFS volumes using Cloud Manager
Now you can create CIFS volumes in FSx for ONTAP using Cloud Manager.

=== Edit volumes using Cloud Manager
Now you can edit FSx for ONTAP volumes using Cloud Manager.

== 2 September 2021
=== Support for Amazon FSx for NetApp ONTAP

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP^] is a fully managed service allowing customers to launch and run file systems powered by NetApp’s ONTAP storage operating system. FSx for ONTAP provides the same features, performance, and administrative capabilities NetApp customers use on premises, with the simplicity, agility, security, and scalability of a native AWS service.
+
link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/concept-fsx-aws.html[Learn about Amazon FSx for NetApp ONTAP].

* You can configure an FSx for ONTAP working environment in Cloud Manager.
+
link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-create-fsx-system.html[Create an Amazon FSx for NetApp ONTAP working environment].

* Using a Connector in AWS and Cloud Manager, you can create and manage volumes, replicate data, and integrate FSx for ONTAP with NetApp cloud services, such as Data Sense and Cloud Sync.
+
link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-fsx.html[Get started with Cloud Data Sense for Amazon FSx for NetApp ONTAP^].
