=== Tracker response support

Tracker now provides API responses so that you can see the REST API output related to the task.

=== Link authentication support for AWS Secrets Manager

You now have the option to use secrets from AWS Secrets Manager to authenticate links so that you don't have to use credentials stored in BlueXP Workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Connect to an FSx for ONTAP file system with a Lambda link^]

=== Implement best practices for an FSx for ONTAP file system

BlueXP Workloads provides a dashboard where you can review the well-architected status of your file system configurations. You can leverage this analysis to implement best practices for your FSx for ONTAP file systems. File system configuration analysis includes the following configurations: SSD capacity threshold, scheduled local snapshots, scheduled FSx for ONTAP backups, data tiering, and remote data replication. 

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html[Learn about the well-architected analysis for file system configurations^]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html[Implement best practices for your file systems^]

=== Well-architected notification for file system issues 

In the BlueXP console, FSx for ONTAP file systems with well-architected issues now display a notification in the Canvas indicating when file systems have issues to fix. 

=== Updated permissions terminology

The workload factory user interface and documentation now use "read-only" to refer to read permissions and "read/write" to refer to automate permissions.