=== Associate FSx for ONTAP file system with a workspace in BlueXP
After BlueXP integration in November 2024, newly created FSx for ONTAP file systems were not associated with one workspace in BlueXP. Now when you create or discover FSx for ONTAP file systems, they are associated with one workspace within a BlueXP account. 

If you have existing FSx for ONTAP file systems that are not associated with a workspace, we will help you associate them with a workspace in BlueXP. You can link:https://docs.netapp.com/us-en/console-setup-admin/task-get-help.html#create-a-case-with-netapp-support[create a case with NetApp Support^] from within the BlueXP console. Select *Workload Factory* as the service. 

=== File system removal from BlueXP canvas 
You can now remove an FSx for ONTAP file system from a workspace in the BlueXP canvas. This operation dissociates the file system from one workspace so that you can associate it with another workspace within the same BlueXP account. 

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-remove-filesystem.html[Learn how to remove an FSx for ONTAP file system from a workspace in BlueXP^]

=== Tracker available for monitoring and tracking operations
Tracker, a new monitoring capability, is available in BlueXP Amazon FSx for NetApp ONTAP. You can use Tracker to monitor and track the progress and status of credentials, storage, and link operations, review details for operation tasks and subtasks, diagnose any issues or failures, edit parameters for failed operations, and retry failed operations.

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-monitor-operations.html[Learn how to monitor and track FSx for ONTAP operations in BlueXP^]

=== CloudShell available in BlueXP Workloads

CloudShell is available when you're in BlueXP Workloads within the BlueXP console. CloudShell allows you to use the AWS and ONTAP credentials you've provided in your BlueXP account and execute AWS CLI commands or ONTAP CLI commands in a shell-like environment.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html[Use CloudShell^]
