---
sidebar: sidebar
permalink: use/task-create-fsx-system.html
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, working environment, availability zones, discover, storage capacity, iops, throughput, security group, security, bluexp, NetApp Console
summary: "Create or discover an FSx for ONTAP file systems to add and manage volumes and additional data services from the NetApp Console."
---

= Create or discover an FSx for ONTAP file system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Create or discover an FSx for ONTAP file system to add and manage volumes and additional data services from the NetApp Console.

== Create an FSx for ONTAP system

The first step is to create an FSx for ONTAP file system. If you already created an FSx for ONTAP file system in the AWS Management Console, you can link:task-create-fsx-system.html#discover-an-existing-fsx-for-ontap-file-system[discover it using the NetApp Console].

.About this task
A storage VM is created when you create a file system. 

.Before you begin
Before creating your FSx for ONTAP file system, you will need:

* The ARN of an IAM role that gives Workload Factory the permissions needed to create an FSx for ONTAP file system. link:../requirements/task-setting-up-permissions-fsx.html[Learn how to grant permissions to an AWS account^].

* The region and VPC information for where you will create the FSx for ONTAP instance.

== Create an FSx for ONTAP file system
You can create an FSx for ONTAP file system using _Quick create_ or _Advanced create_. You can also use the following tools available in the Codebox: REST API, CloudFormation, and Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox[Learn how to use Codebox for automation^]. 

NOTE: When using Terraform from Codebox, the code you copy or download hides `fsxadmin` and `vsadmin` passwords. You'll need to re-enter the passwords when you run the code.  

[role="tabbed-block"]
====

.Quick create
--
Quick create enables you to use a recommended best-practice configuration. You can change most settings after you create an FSx for ONTAP file system. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
include::https://raw.githubusercontent.com/NetAppDocs/workload-fsx-ontap/main/_include/create-file-system-quick-create.adoc[]

.Result
If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].
--

.Advanced create
--
With Advanced create, you set all of the configuration options, including availability, security, backups, and maintenance. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
include::https://raw.githubusercontent.com/NetAppDocs/workload-fsx-ontap/main/_include/create-file-system-advanced-create.adoc[]

.Result

If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].
--

====


== Discover an existing FSx for ONTAP file system 

If you previously provided your AWS credentials in the NetApp Console, you can automatically discover FSx for ONTAP file systems from the Discoverable systems page. You can also review available data services. 

.About this task
You can discover an FSx for ONTAP file system only once within an account and attach it to one workspace. The file system can later be removed and re-associated to a different workspace.

.Steps

. From the NetApp Console menu, select *Storage*, then *Management*, and then *Discoverable systems*. 

. The count of discovered FSx for ONTAP file systems displays. Select *Discover*.  

. Select one or more file systems and select *Discover* to add them to the Systems page. 

[NOTE]
===============================
* If you select an un-named cluster, you will receive a prompt to enter a name for the cluster.

* If you select a cluster that doesn't have the credentials required to manage the FSx for ONTAP file system from the Console, you'll receive a prompt to select credentials with the required permissions. 

* The following regions aren't supported for discovery: China regions, GovCloud (US) regions, Secret Cloud, and Top Secret Cloud.
===============================

.Result

The Console displays your discovered FSx for ONTAP file system on the Systems page. You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].