---
sidebar: sidebar
permalink: use/task-create-fsx-system.html
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, working environment, availability zones, discover, storage capacity, iops, throughput, security group, security, bluexp, NetApp Console
summary: "Create or discover an FSx for ONTAP file systems to add and manage volumes and additional data services from the NetApp Console."
---

= Create or discover an FSx for ONTAP file system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Create or discover an FSx for ONTAP file system to add and manage volumes and additional data services from the NetApp Console.

== Create an FSx for ONTAP system

The first step is to create an FSx for ONTAP file system. If you already created an FSx for ONTAP file system in the AWS Management Console, you can link:task-create-fsx-system.html#discover-an-existing-fsx-for-ontap-file-system[discover it using the NetApp Console].

.About this task
A storage VM is created when you create a file system. 

.Before you begin
Before creating your FSx for ONTAP file system, you will need:

* The ARN of an IAM role that gives Workload Factory the permissions needed to create an FSx for ONTAP file system. link:../requirements/task-setting-up-permissions-fsx.html[Learn how to grant permissions to an AWS account^].

* The region and VPC information for where you will create the FSx for ONTAP instance.

== Create an FSx for ONTAP file system
You can create an FSx for ONTAP file system using _Quick create_ or _Advanced create_. You can also use the following tools available in the Codebox: REST API, CloudFormation, and Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox[Learn how to use Codebox for automation^]. 

NOTE: When using Terraform from Codebox, the code you copy or download hides `fsxadmin` and `vsadmin` passwords. You'll need to re-enter the passwords when you run the code.  

[role="tabbed-block"]
====

.Quick create
--
Quick create enables you to use a recommended best-practice configuration. You can change most settings after you create an FSx for ONTAP file system. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
. On the Create FSx for ONTAP file system page, select *Quick create*. 
+
You can also load a saved configuration.
. Under File system general configuration, provide the following: 
.. *AWS credentials*: Select to add AWS credentials or continue without credentials. Without credentials, you can copy and download the partially complete code from the Codebox. The code can be used like a template where you can fill in missing information (for example, credentials) or customize certain data before running the code.
.. *File system name*: Enter a name for the file system. 
.. *Deployment topology*: Select a deployment topology. 
+
* Scale-up topology is where one file system is used for data distribution and can increase in size to accommodate data growth.
* Scale-out topology is where more than one file system is used for data distribution. 
.. *HA pairs*: Enter the number of HA pairs.
+
* For scale-up deployments, you can only have one HA pair. 
* For scale-out deployments, you can have between two and twelve HA pairs.
.. *Deployment type*: Select a deployment type.
+
* Single Availability Zone (Single-AZ) deployment: ensures availability by monitoring for hardware failures and automatically replacing infrastructure components in the event of a failure. Achieves high durability by automatically replicating your data within an Availability Zone to protect it from component failure.
+
* Multiple Availability Zones (Multi-AZ) deployment: provides continuous availability to data even when an Availability Zone is unavailable. Multi-AZ file systems support all the availability and durability features of Single-AZ file systems. A Multi-AZ file system is designed for business-critical production workloads that require high availability to shared ONTAP file data and need storage with built-in replication across Availability Zones.
.. *Tags*: Optionally, you can add up to 50 tags. 
. Under *Network & security*, in the *Region & VPC* field, select the region and VPC for the file system. 
. Under *File system details*, provide the following: 
.. *SSD storage capacity*: Enter the storage capacity and select the storage capacity unit. 
.. *ONTAP credentials*: Enter your ONTAP user name and password.  
.. *SMB/CIFS setup*: Optional. If you plan to use SMB/CIFS protocol to access volumes, you must configure the Active Directory for the storage VM during file system creation. Provide the following details for the storage VM that is created for this file system. 
... *Active Directory domain to join*: Enter the fully qualified domain name (FQDN) for the Active Directory.
... *DNS IP addresses*: Enter up to three DNS IP addresses separated by commas. 
... *SMB server NetBIOS name*: Enter the SMB server NetBIOS name of the Active Directory computer object to create for your storage VM. This is the name of this storage VM in the Active Directory.
... *User name*: Enter the user name of the service account in your existing Active Directory. 
+
Do not include a domain prefix or suffix. For `EXAMPLE\ADMIN`, use `ADMIN`.
... *Password*: Enter the password for the service account. 
... *Organization unit*: Optionally, enter the name of the Organizational Unit where you intend to create the computer account for FSx for ONTAP. The OU is the distinguished path name of the organizational unit to which you want to join the file system. 
... *Delegated administrators group*: Optionally, enter the name of the group in your Active Directory that can administer your file system.
+
If you are using AWS Managed Microsoft AD, you must specify a group such as AWS Delegated FSx Administrators, AWS Delegated Administrators, or a custom group with delegated permissions to the OU.
+
If you are joining to a self-managed AD, use the name of the group in your AD. The default group is `Domain Admins`.

. Open the *Summary* to review the configuration that you defined. If needed, you can change any setting at this time before saving or creating the file system. 
. Save or create the file system. 

.Result
If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].
--

.Advanced create
--
With Advanced create, you set all of the configuration options, including availability, security, backups, and maintenance. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
. On the Create FSx for ONTAP page, select *Advanced create*. 
+
You can also load a saved configuration.
. Under File system general configuration, provide the following: 
.. *AWS credentials*: Select to add AWS credentials in Workload Factory or continue without credentials. 
.. *File system name*: Enter a name for the file system. 
.. *Deployment topology*: Select a deployment topology. 
+
* Scale-up topology is where one file system is used for data distribution and can increase in size to accommodate data growth.
* Scale-out topology is where more than one file system is used for data distribution. 
.. *HA pairs*: Enter the number of HA pairs.
+
* For scale-up deployments, you can only have one HA pair. 
* For scale-out deployments, you can have between two and twelve HA pairs.
.. *Deployment type*: Select a deployment type.
+
* Single Availability Zone (Single-AZ) deployment: ensures availability by monitoring for hardware failures and automatically replacing infrastructure components in the event of a failure. Achieves high durability by automatically replicating your data within an Availability Zone to protect it from component failure.
+
* Multiple Availability Zones (Multi-AZ) deployment: provides continuous availability to data even when an Availability Zone is unavailable. Multi-AZ file systems support all the availability and durability features of Single-AZ file systems. A Multi-AZ file system is designed for business-critical production workloads that require high availability to shared ONTAP file data and need storage with built-in replication across Availability Zones.
.. *Tags*: Optionally, you can add up to 50 tags. 
. Under Network & security, provide the following: 
.. *Region & VPC*: Select the region and VPC for the file system. 
.. *Security group*: Create or use an existing security group.
.. *Availability Zones*: Select availability zones and subnets.
+
* For Cluster configuration node 1: Select an availability zone and subnet. 
* For Cluster configuration node 2: Select an availability zone and subnet. 
.. *VPC route tables*: Select the VPC route table to enable client access to volumes. 
.. *Endpoint IP address range*: Select *Floating IP address range outside your VPC* or *Enter an IP address range* and enter an IP address range. 
.. *Encryption*: Select the encryption key name from the dropdown.
. Under File system details, provide the following: 
.. *SSD storage capacity*: Enter the storage capacity and select the storage capacity unit. 
.. *Provisioned IOPS*: Select *Automatic* or *User-provisioned*. 
.. *Throughput capacity per HA pair*: Select throughput capacity per HA pair. 
.. *ONTAP credentials*: Enter your ONTAP user name and password.
.. *Storage VM Credentials*: Enter your user name. Password can be specific to this file system or you case use the same password entered for ONTAP credentials.
.. *SMB/CIFS setup*: Optional. If you plan to use SMB/CIFS protocol to access volumes, you must configure the Active Directory for the storage VM during file system creation. Provide the following details for the storage VM that is created for this file system. 
... *Active Directory domain to join*: Enter the fully qualified domain name (FQDN) for the Active Directory.
... *DNS IP addresses*: Enter up to three DNS IP addresses separated by commas. 
... *SMB server NetBIOS name*: Enter the SMB server NetBIOS name of the Active Directory computer object to create for your storage VM. This is the name of this storage VM in the Active Directory.
... *User name*: Enter the user name of the service account in your existing Active Directory. 
+
Do not include a domain prefix or suffix. For `EXAMPLE\ADMIN`, use `ADMIN`.
... *Password*: Enter the password for the service account. 
... *Organization unit*: Optionally, enter the name of the Organizational Unit where you intend to create the computer account for FSx for ONTAP. The OU is the distinguished path name of the organizational unit to which you want to join the file system. 
... *Delegated administrators group*: Optionally, enter the name of the group in your Active Directory that can administer your file system.
+
If you are using AWS Managed Microsoft AD, you must specify a group such as AWS Delegated FSx Administrators, AWS Delegated Administrators, or a custom group with delegated permissions to the OU.
+
If you are joining to a self-managed AD, use the name of the group in your AD. The default group is `Domain Admins`.
. Under Backup and maintenance, provide the following: 
.. *FSx for ONTAP Backup*: Daily automatic backups are enabled by default. Disable if desired. 
... *Automatic backup retention period*: Enter the number of days to retain automatic backups. 
... *Daily automatic backup window*: Select either *No preference* (a daily backup start time is selected for you) or *Select start time for daily backups* and specify a start time. 
... *Weekly maintenance window*: Select either *No preference* (a weekly maintenance window start time is selected for you) or *Select start time for 30-minute weekly maintenance window* and specify a start time.  
. Save or create the file system. 

.Result

If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].
--

====


== Discover an existing FSx for ONTAP file system 

If you previously provided your AWS credentials in the NetApp Console, you can automatically discover FSx for ONTAP file systems from the Discoverable systems page. You can also review available data services. 

.About this task
You can discover an FSx for ONTAP file system only once within an account and attach it to one workspace. The file system can later be removed and re-associated to a different workspace.

.Steps

. From the NetApp Console menu, select *Storage*, then *Management*, and then *Discoverable systems*. 

. The count of discovered FSx for ONTAP file systems displays. Select *Discover*.  

. Select one or more file systems and select *Discover* to add them to the Systems page. 

[NOTE]
===============================
* If you select an un-named cluster, you will receive a prompt to enter a name for the cluster.

* If you select a cluster that doesn't have the credentials required to manage the FSx for ONTAP file system from the Console, you'll receive a prompt to select credentials with the required permissions. 

* The following regions aren't supported for discovery: China regions, GovCloud (US) regions, Secret Cloud, and Top Secret Cloud.
===============================

.Result

The Console displays your discovered FSx for ONTAP file system on the Systems page. You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation. Learn how to link:task-manage-fsx-systems.html[manage an FSx for ONTAP file system].